-- Run this script in your Supabase SQL Editor to prepare the database for the Admin Dashboard features

-- 1. Create categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow admin write access to categories" ON public.categories 
  FOR ALL USING (
    auth.uid() IN (
      SELECT id FROM public.profiles WHERE role = 'admin'
    )
  );

-- Insert default categories to migrate the hardcoded array from the frontend
INSERT INTO public.categories (name) VALUES 
('All'),
('Web Development'),
('Cyber Security'),
('Graphic Design'),
('Digital Marketing'),
('App Development')
ON CONFLICT (name) DO NOTHING;


-- 2. Update courses table to include category support
-- We will add a category_id linking to the new categories table
ALTER TABLE public.courses
ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL;

-- Make sure admin can write to courses (previous policy might have been select only)
-- Drop existing write policies if any, then recreate
DROP POLICY IF EXISTS "Allow admin write access to courses" ON public.courses;
CREATE POLICY "Allow admin write access to courses" ON public.courses 
  FOR ALL USING (
    auth.uid() IN (
      SELECT id FROM public.profiles WHERE role = 'admin'
    )
  );


-- 3. Create hero_slides table
CREATE TABLE IF NOT EXISTS public.hero_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for hero_slides
ALTER TABLE public.hero_slides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to active hero_slides" ON public.hero_slides FOR SELECT USING (is_active = true);
CREATE POLICY "Allow admin read access to all hero_slides" ON public.hero_slides 
  FOR SELECT USING (
    auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin')
  );
CREATE POLICY "Allow admin write access to hero_slides" ON public.hero_slides 
  FOR ALL USING (
    auth.uid() IN (
      SELECT id FROM public.profiles WHERE role = 'admin'
    )
  );

-- Insert initial slides to migrate hardcoded ones
INSERT INTO public.hero_slides (image_url) VALUES 
('https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80'),
('https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80'),
('https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80');
