-- 1. Create normalized modules table
CREATE TABLE IF NOT EXISTS public.modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.modules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access to modules" ON public.modules;
CREATE POLICY "Allow public read access to modules" ON public.modules FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admin write access to modules" ON public.modules;
CREATE POLICY "Allow admin write access to modules" ON public.modules FOR ALL USING (auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin'));

-- 2. Create normalized lessons_new table
CREATE TABLE IF NOT EXISTS public.lessons_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT REFERENCES public.modules(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content_text TEXT,
    video_url TEXT,
    pdf_url TEXT,
    support_file_url TEXT,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.lessons_new ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access to lessons_new" ON public.lessons_new;
CREATE POLICY "Allow public read access to lessons_new" ON public.lessons_new FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admin write access to lessons_new" ON public.lessons_new;
CREATE POLICY "Allow admin write access to lessons_new" ON public.lessons_new FOR ALL USING (auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin'));

-- 3. Seed data
DO $$ 
DECLARE
  v_course_id BIGINT;
  v_mod1_id BIGINT;
  v_mod2_id BIGINT;
  v_mod3_id BIGINT;
  v_mod4_id BIGINT;
  v_mod5_id BIGINT;
  v_mod6_id BIGINT;
  v_mod7_id BIGINT;
  v_mod8_id BIGINT;
  v_mod9_id BIGINT;
  v_mod10_id BIGINT;
  v_mod11_id BIGINT;
BEGIN
  -- Insert course if not exists
  SELECT id INTO v_course_id FROM public.courses WHERE title = 'Competency-Based Training & Assessment';
  
  IF v_course_id IS NULL THEN
    INSERT INTO public.courses (title, description, instructor_name, modules_count, duration, image_url)
    VALUES ('Competency-Based Training & Assessment', 'Official CBT&A course covering all 11 core modules for trainers and assessors.', 'CBT&A Admin', 11, '6 Months', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=600&q=80')
    RETURNING id INTO v_course_id;
  END IF;

  -- Clear existing modules for this course to ensure clean seed (Cascades to lessons_new)
  DELETE FROM public.modules WHERE course_id = v_course_id;

  -- Insert Modules
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 1: Receive and Respond to Workplace Communication', 1) RETURNING id INTO v_mod1_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 2: Work with Others', 2) RETURNING id INTO v_mod2_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 3: Demonstrate Work Values', 3) RETURNING id INTO v_mod3_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 4: Practice Career Professionalism', 4) RETURNING id INTO v_mod4_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 5: Practice Occupational Health and Safety Procedures', 5) RETURNING id INTO v_mod5_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 6: Interpret Technical Drawings and Specifications', 6) RETURNING id INTO v_mod6_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 7: Apply Quality Standards', 7) RETURNING id INTO v_mod7_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 8: Perform Computer Operations', 8) RETURNING id INTO v_mod8_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 9: Use Relevant Technologies', 9) RETURNING id INTO v_mod9_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 10: Clean and Maintain Work Area and Machines', 10) RETURNING id INTO v_mod10_id;
  INSERT INTO public.modules (course_id, title, order_index) VALUES (v_course_id, 'Module 11: Implement Competency-Based Training and Assessment (Core)', 11) RETURNING id INTO v_mod11_id;

  -- Seed Module 1 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod1_id, 'Introduction to Workplace Communication', 'Overview of effective communication strategies in the workplace.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'https://docs.google.com/document/d/dummy-assignment/edit', 1),
  (v_mod1_id, 'Interpreting Information', 'Techniques for accurately interpreting written and verbal information.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 2 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod2_id, 'Developing Effective Workplace Relationships', 'Building trust and collaboration within a team.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod2_id, 'Contributing to Team Work', 'Your role and responsibilities in achieving team objectives.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 3 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod3_id, 'Defining Professional Integrity', 'Understanding the core components of professional integrity.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod3_id, 'Maintaining Workplace Ethics', 'How to handle ethical dilemmas at work.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 4 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod4_id, 'Integrating Personal and Organizational Goals', 'Aligning your career goals with the organization.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod4_id, 'Professional Development', 'Continuous learning and skill enhancement strategies.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 5 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod5_id, 'Identifying Workplace Hazards', 'Recognizing potential OHS risks and hazards.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'https://docs.google.com/spreadsheets/d/dummy-safety-checklist/edit', 1),
  (v_mod5_id, 'Implementing OHS Control Measures', 'Actionable steps to mitigate safety risks.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 6 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod6_id, 'Introduction to Technical Blueprints', 'Basics of reading technical drawings.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod6_id, 'Reading Design Schematics', 'Advanced schematic interpretation.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 7 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod7_id, 'Assessing Quality of Received Materials', 'Quality control and material inspection standards.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod7_id, 'Conforming to Production Standards', 'Ensuring consistent output quality.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 8 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod8_id, 'Hardware and Software Basics', 'Essential IT knowledge for the modern workplace.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod8_id, 'Managing Files and Data Security', 'Best practices for data protection.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 9 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod9_id, 'Selecting Appropriate Tools', 'How to choose the right technology for the job.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod9_id, 'Operating Specialized Systems', 'Training on specific technological applications.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 10 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod10_id, 'Housekeeping and 5S Methodologies', 'Keeping the workspace organized and safe.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', null, 1),
  (v_mod10_id, 'Routine Machine Preventive Maintenance', 'Basic machine maintenance protocols.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

  -- Seed Module 11 Lessons
  INSERT INTO public.lessons_new (module_id, title, content_text, video_url, pdf_url, support_file_url, order_index) VALUES 
  (v_mod11_id, 'Understanding CBT Delivery', 'Core concepts of Competency-Based Training.', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'https://docs.google.com/document/d/dummy-assessment-form/edit', 1),
  (v_mod11_id, 'Conducting Competency Assessment', 'Methods and tools for effective assessment.', 'https://www.w3schools.com/html/mov_bbb.mp4', null, null, 2);

END $$;
