-- 1. Create profiles table
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Function to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. Update courses table (Drop existing if needed and recreate, or alter)
DROP TABLE IF EXISTS public.lessons CASCADE;
DROP TABLE IF EXISTS public.user_progress CASCADE;
DROP TABLE IF EXISTS public.courses CASCADE;

CREATE TABLE public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    instructor_name TEXT NOT NULL,
    modules_count INTEGER DEFAULT 0,
    duration TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to courses" ON public.courses FOR SELECT USING (true);


-- 3. Create lessons table
CREATE TABLE public.lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    video_url TEXT,
    pdf_url TEXT,
    module_title TEXT NOT NULL,
    duration TEXT, -- Optional: helpful for UI
    lesson_order INTEGER DEFAULT 0, -- To keep lessons ordered
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to lessons" ON public.lessons FOR SELECT USING (true);


-- 4. Recreate user_progress table
CREATE TABLE public.user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    progress_percentage INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, course_id)
);

ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own progress" ON public.user_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own progress" ON public.user_progress FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own progress" ON public.user_progress FOR INSERT WITH CHECK (auth.uid() = user_id);


-- Insert initial mock data into courses
INSERT INTO public.courses (id, title, description, instructor_name, modules_count, duration, image_url)
VALUES 
(1, 'Professional Web Development', 'Master HTML, CSS, and modern JavaScript frameworks.', 'MD RAKIB HOSSAIN', 24, '3 Months', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80'),
(2, 'Digital Marketing Mastery', 'Learn SEO, SEM, and social media strategies.', 'MD RAKIB HOSSAIN', 18, '2 Months', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80'),
(3, 'Graphic Design Fundamentals', 'An introduction to design principles and tools.', 'MD RAKIB HOSSAIN', 12, '6 Weeks', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80');

-- Reset course ID sequence since we forced IDs
SELECT setval('courses_id_seq', 3);

-- Insert mock data into lessons for Course 1
INSERT INTO public.lessons (course_id, module_title, title, video_url, pdf_url, duration, lesson_order)
VALUES
(1, 'Module 1: Introduction', 'Course Overview', 'https://www.w3schools.com/html/mov_bbb.mp4', null, '5 mins', 1),
(1, 'Module 1: Introduction', 'Setup Environment', 'https://www.w3schools.com/html/mov_bbb.mp4', null, '12 mins', 2),
(1, 'Module 1: Introduction', 'HTML Cheat Sheet', null, 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', '1 MB', 3),
(1, 'Module 2: Advanced Concepts', 'CSS Grid & Flexbox', 'https://www.w3schools.com/html/mov_bbb.mp4', null, '20 mins', 4),
(1, 'Module 2: Advanced Concepts', 'JavaScript ES6+', 'https://www.w3schools.com/html/mov_bbb.mp4', null, '45 mins', 5);
