-- Create the courses table
CREATE TABLE public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    instructor TEXT NOT NULL,
    modules_count INTEGER DEFAULT 0,
    duration TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- Allow anonymous and authenticated users to read courses
CREATE POLICY "Allow public read access to courses" 
ON public.courses FOR SELECT 
USING (true);


-- Create the user_progress table
CREATE TABLE public.user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    progress_percentage INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, course_id)
);

-- Enable Row Level Security
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own progress
CREATE POLICY "Users can view their own progress" 
ON public.user_progress FOR SELECT 
USING (auth.uid() = user_id);

-- Allow users to update their own progress
CREATE POLICY "Users can update their own progress" 
ON public.user_progress FOR UPDATE 
USING (auth.uid() = user_id);

-- Allow users to insert their own progress
CREATE POLICY "Users can insert their own progress" 
ON public.user_progress FOR INSERT 
WITH CHECK (auth.uid() = user_id);


-- Insert initial mock data into courses
INSERT INTO public.courses (title, instructor, modules_count, duration, image_url)
VALUES 
('Professional Web Development', 'MD RAKIB HOSSAIN', 24, '3 Months', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80'),
('Digital Marketing Mastery', 'MD RAKIB HOSSAIN', 18, '2 Months', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80'),
('Graphic Design Fundamentals', 'MD RAKIB HOSSAIN', 12, '6 Weeks', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80');

-- NOTE FOR THE USER: 
-- Once you log in with a user in your application, you will need to manually insert a row into `user_progress` 
-- in the Supabase Dashboard, mapping your `user_id` to a `course_id` (e.g., 1 or 2) to see data on the Profile page.
